Sparse Matrix With Scipy

In [1]:
#Import statements 
import numpy as np 
from scipy.sparse import csr_matrix 
from scipy.sparse import coo_matrix 
from scipy.sparse import csc_matrix  

COO format

In [2]:
## Create a 2D numpy array with a lot of zeros 
dense_matrix = np.array([
    [0, 0, 0, 1],
    [2, 0, 0, 3],
    [0, 4, 0, 0],
    [1, 2, 5, 0]
])



In [3]:
dense_matrix

array([[0, 0, 0, 1],
       [2, 0, 0, 3],
       [0, 4, 0, 0],
       [1, 2, 5, 0]])

In [4]:
#Convert the dense matrix to COO format 
sparse_matrix_coo = coo_matrix(dense_matrix)
sparse_matrix_coo

<COOrdinate sparse matrix of dtype 'int64'
	with 7 stored elements and shape (4, 4)>

In [5]:
#Print out the internal data structure of the COO matrix
print("Data array:", sparse_matrix_coo.data)
print("Row Indices array :", sparse_matrix_coo.row)
print("Column Indices array array:", sparse_matrix_coo.col)

Data array: [1 2 3 4 1 2 5]
Row Indices array : [0 1 1 2 3 3 3]
Column Indices array array: [3 0 3 1 0 1 2]


In [ ]:
#We can not perform aritmetic operations with this format
# By exemple below sparse_matrix_coo[1:3, :]will throw an error

In [6]:
#Perform row slicing 
sparse_matrix_coo[1:3, :]

TypeError: 'coo_matrix' object is not subscriptable

In [8]:
# sparse_matrix_coo.ded 

CSR Format

In [11]:
## Create a 2D numpy array with a lot of zeros 
dense_matrix = np.array([
    [0, 0, 0, 1],
    [2, 0, 0, 3],
    [0, 4, 0, 0],
    [1, 2, 5, 0]
])
#Convert the dense matrix to CSR format
sparse_matrix_csr = csr_matrix(dense_matrix)
print(dense_matrix)

#Print out the internal data structure of the CSR matrix
print("Data array:", sparse_matrix_csr.data)
print("Indices array :", sparse_matrix_csr.indices)
print("Indptr array:", sparse_matrix_csr.indptr)

[[0 0 0 1]
 [2 0 0 3]
 [0 4 0 0]
 [1 2 5 0]]
Data array: [1 2 3 4 1 2 5]
Indices array : [3 0 3 1 0 1 2]
Indptr array: [0 1 3 4 7]


In [12]:
#Perform row slicing 
row_slice = sparse_matrix_csr[1:3, :]
print("Row slice:")
print(row_slice.toarray())

Row slice:
[[2 0 0 3]
 [0 4 0 0]]


CSC Format


In [ ]:
## Create a 2D numpy array with a lot of zeros 
dense_matrix = np.array([
    [0, 0, 0, 1],
    [2, 0, 0, 3],
    [0, 4, 0, 0],
    [1, 2, 5, 0]
])
#Convert the dense matrix to CSC format
sparse_matrix_csc = csc_matrix(dense_matrix)
print(sparse_matrix_csc)

#Print out the internal data structure of the CSC matrix
print("Data array:", sparse_matrix_csc.data)
print("Indices array :", sparse_matrix_csc.indices)
print("Indptr array:", sparse_matrix_csc.indptr)

<Compressed Sparse Column sparse matrix of dtype 'int64'
	with 7 stored elements and shape (4, 4)>
  Coords	Values
  (1, 0)	2
  (3, 0)	1
  (2, 1)	4
  (3, 1)	2
  (3, 2)	5
  (0, 3)	1
  (1, 3)	3
Data array: [2 1 4 2 5 1 3]
Indices array : [1 3 2 3 3 0 1]
Indptr array: [0 2 4 5 7]


In [14]:
sparse_matrix_csc.toarray()

array([[0, 0, 0, 1],
       [2, 0, 0, 3],
       [0, 4, 0, 0],
       [1, 2, 5, 0]])

In [15]:
sparse_matrix_csc.tocoo()

<COOrdinate sparse matrix of dtype 'int64'
	with 7 stored elements and shape (4, 4)>

In [16]:
sparse_matrix_csc.tocsc()

<Compressed Sparse Column sparse matrix of dtype 'int64'
	with 7 stored elements and shape (4, 4)>

In [17]:
sparse_matrix_coo.eliminate_zeros()